variables:
  BASE_BRANCH: "master"
  CACHE_S3_PREFIX: "stack"
  CACHE_S3_VERSION: "v0.1.4"
  S3_BUCKET: "azure-wsm-cache-ci-cache"
  AWS_REGION: "us-east-1"

jobs:
- template: azure-pipeline-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13
    os: osx

- template: azure-pipeline-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    os: linux

- template: azure-windows-template.yml
  parameters:
   name: Windows
   vmImage: vs2017-win2016
   os: windows
