build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"

  matrix:
  - ARGS: ""
  #- ARGS: "--resolver lts-2"
  #- ARGS: "--resolver lts-3"
  #- ARGS: "--resolver lts-6"
  #- ARGS: "--resolver lts-7"
  - ARGS: "--resolver lts-9"
  - ARGS: "--resolver lts-11"
  #- ARGS: "--resolver nightly"

test_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal test
